.github/ISSUE_TEMPLATE/issue-template.md
=> issue templete

src/main/java/com/kosa/controller/HomeController.java
=> [feat] test #6

src/main/webapp/WEB-INF/views/home.jsp
=> [feat] home.jsp 수정 test #9

src/main/java/com/kosa/controller/HomeController.java
=> [feat] test #10

pom.xml
=> [fix] ojdbc 버전변경 (#17)

src/main/java/com/kosa/mapper/MemberMapper.java, src/main/resources/com/kosa/mapper/MemberMapper.xml
member에 관련된 mapper와 mapper.xml 생성
resolved #23
=> [feat] MemberMapper (#23)

src/main/java/com/kosa/mapper/MemberMapper.java, src/main/resources/com/kosa/mapper/MemberMapper.xml
MemberMapper 테스트시 오류 나는 부분 수정
resolved #26
=> [fix] membermapper 수정

src/main/webapp/WEB-INF/spring/root-context.xml
root-context.xml user 정보 수정
user명 team5
resolved #29
=> [fix] root-context.xml user정보 수정

src/main/java/com/kosa/domain/member/MemberVO.java, src/main/java/com/kosa/service/MemberService.java, src/main/java/com/kosa/service/MemberServicelmpl.java, src/main/resources/com/kosa/mapper/MemberMapper.xml, src/test/java/com/kosa/service/MemberServicelpmlTest.java
memberService로 회원 비즈니스 로직 생성 및 Test 수행
추가 -> memberVO와 Mapper 수정
resovled #37
=> Feature member/member service(#37)

src/main/java/com/kosa/domain/order/Criteria.java, src/main/java/com/kosa/domain/order/OrdersVO.java, src/main/java/com/kosa/mapper/OrderMapper.java, src/main/resources/com/kosa/mapper/OrderMapper.xml, src/test/java/com/kosa/mapper/OrderMapperTest.java
=> [feat] OrderMapper 생성 및 테스트 (#25)

src/main/java/com/kosa/domain/order/OrderItemVO.java, src/main/java/com/kosa/domain/order/OrdersVO.java, src/main/java/com/kosa/domain/product/ProductDetailVO.java, src/main/resources/com/kosa/mapper/OrderMapper.xml, src/test/java/com/kosa/mapper/OrderMapperTest.java
=> [feat] order mapper 생성 및 테스트 (#25)

src/main/java/com/kosa/domain/member/CartVO.java, src/main/java/com/kosa/mapper/CartMapper.java, src/main/java/com/kosa/service/CartServiceImpl.java, src/main/resources/com/kosa/mapper/CartMapper.xml, src/test/java/com/kosa/mapper/CartMapperTests.java
cartMapper.xml의 sql문 수정
행이 하나밖에 조회가 안되는 것을 resultMap으로 수정하여 여러행 조회가능하게 변경
mapper, service test까지 완료
close #45
=> [fix] cart select sql (#45)

src/main/java/com/kosa/controller/EventController.java, src/main/java/com/kosa/domain/event/EventVO.java, src/main/java/com/kosa/domain/event/EventViewVO.java, src/main/java/com/kosa/service/EventService.java, src/main/java/com/kosa/service/EventServiceImpl.java, src/main/resources/com/kosa/mapper/EventMapper.xml, src/main/webapp/WEB-INF/views/magazine/event.jsp, src/test/java/com/kosa/controller/EventViewControllertest.java, src/test/java/com/kosa/mapper/EventViewMapperTest.java, src/test/java/com/kosa/service/EventViewServiceTest.java
=> [feat] event(#16)

src/main/java/com/kosa/mapper/EventMapper.java, src/main/java/com/kosa/service/EventService.java, src/main/java/com/kosa/service/EventServiceImpl.java, src/main/resources/com/kosa/mapper/EventMapper.xml, src/test/java/com/kosa/mapper/EventViewMapperTest.java
=> [fix] 이벤트 버그 fix (#57)

src/main/resources/com/kosa/mapper/MemberMapper.xml, src/test/java/com/kosa/mapper/MemberMapperTest.java
membermapper xml 수정 및 테스트 완료
resovled #64
=> [fix] membermapper Edit (#64)

src/main/java/com/kosa/domain/member/MemberVO.java, src/main/java/com/kosa/service/MemberService.java, src/main/java/com/kosa/service/MemberServicelmpl.java, src/test/java/com/kosa/service/MemberServicelpmlTest.java
- member join edit
- member passwordcheck add
resovled #66
=> [feat] memberService join edit, passwordcheck add (#66)

src/main/java/com/kosa/controller/MemberController.java, src/main/java/com/kosa/controller/MemberRestController.java
memberController 추가
memberRestController 추가
resovled #68
=> [feat] memberController add (#68)

pom.xml, src/main/webapp/WEB-INF/spring/root-context.xml
- pom.xml : Mail dependencies 추가
- root-context.xml : JavaMail Bean 등록
resolved #72
=> [feat] JavaMail SpringBean and dependencies add(#72)

src/main/java/com/kosa/controller/EventController.java, src/main/java/com/kosa/controller/MypageController2.java, src/main/java/com/kosa/domain/event/CouponDetailVO.java, src/main/java/com/kosa/domain/event/CouponDetailViewVO.java, src/main/java/com/kosa/domain/event/EventDetailViewVO.java, src/main/java/com/kosa/domain/event/EventVO.java, src/main/java/com/kosa/domain/event/EventViewVO.java, src/main/java/com/kosa/mapper/EventMapper.java, src/main/java/com/kosa/service/EventService.java, src/main/java/com/kosa/service/EventServiceImpl.java, src/main/resources/com/kosa/mapper/EventMapper.xml, src/main/webapp/WEB-INF/views/common/header.jsp, src/main/webapp/WEB-INF/views/magazine/event.jsp, src/main/webapp/WEB-INF/views/magazine/eventdetail.jsp, src/main/webapp/WEB-INF/views/mypage/mycoupon.jsp, src/test/java/com/kosa/controller/CouponDetailControllerTest.java, src/test/java/com/kosa/controller/EventDetailControllertest.java, src/test/java/com/kosa/mapper/CouponDetailTest.java, src/test/java/com/kosa/mapper/EventDetailTest.java, src/test/java/com/kosa/service/CouponDetailServiceTest.java
=> [feat] event and coupon (#77)

src/main/java/com/kosa/controller/HomeController.java, src/main/java/com/kosa/controller/MyWishController.java, src/main/java/com/kosa/controller/ProductController.java, src/main/java/com/kosa/domain/member/LikesVO.java, src/main/java/com/kosa/domain/paging/Criteria.java, src/main/java/com/kosa/domain/paging/WishPageDTO.java, src/main/java/com/kosa/mapper/MyWishMapper.java, src/main/java/com/kosa/service/MyWishService.java, src/main/java/com/kosa/service/MyWishServiceImpl.java, src/main/resources/com/kosa/mapper/MyWishMapper.xml, src/main/webapp/WEB-INF/views/mypage/mywish.jsp, src/main/webapp/WEB-INF/views/product/productdetail.jsp, src/main/webapp/WEB-INF/views/product/productlist.jsp, src/test/java/com/kosa/mapper/MyWishMapperTest.java, src/test/java/com/kosa/mapper/OrderMapperTest.java, src/test/java/com/kosa/service/MyWishServiceTest.java
=> Feature wish/wish list(#80)

src/main/java/com/kosa/controller/CartRestController.java, src/main/java/com/kosa/mapper/CartMapper.java, src/main/java/com/kosa/service/CartService.java, src/main/java/com/kosa/service/CartServiceImpl.java, src/main/resources/com/kosa/mapper/CartMapper.xml, src/main/webapp/WEB-INF/views/cart/cart.jsp, src/main/webapp/WEB-INF/views/checkout/ordersheetTest.jsp, src/main/webapp/resources/js/handsome/cartlist.js, src/main/webapp/resources/js/handsome/checkoutCartView.js, src/test/java/com/kosa/mapper/CartMapperTests.java, src/test/java/com/kosa/service/CartServiceImplTest.java
- 주문페이지에서 선택항목 카트에 띄우기
- 선택에따라 가격 표시
- 개별삭제
- 선택항목삭제
=> Featuer cart/jsp(#60)

src/main/java/com/kosa/controller/CartRestController.java, src/main/webapp/WEB-INF/views/cart/cart.jsp, src/main/webapp/resources/js/handsome/cartlist.js
=> [fix] 장바구니화면 수정  (#60)

src/main/java/com/kosa/controller/MemberController.java, src/main/java/com/kosa/controller/MemberRestController.java, src/main/resources/com/kosa/mapper/MemberMapper.xml, src/main/webapp/WEB-INF/views/member/joininfoform.jsp
- 회원 가입시 인증 받은 이메일을 회원 아이디로 가입하기 위한 기능
- 세션에 넣어서 회원가입 폼 페이지에서 read only로 출력
- mapper, controller, jsp 수정
- resovled #89
=> Feature member/join form edit(#89)

src/main/java/com/kosa/service/MemberService.java, src/main/java/com/kosa/service/MemberServicelmpl.java, src/main/webapp/WEB-INF/views/member/joinstart.jsp
- 이메일 인증시 해당 이메일 중복확인
- 아이디로 사용될 것이기에 db에서 같은 이메일 아이디가 있는지 확인
resovled #88
=> Feature member/dupl email check(#88)

src/main/java/com/kosa/controller/MypageController.java, src/main/java/com/kosa/controller/MypageRestController.java, src/main/java/com/kosa/mapper/OrderMapper.java, src/main/java/com/kosa/service/OrderServiceImpl.java, src/main/resources/com/kosa/mapper/OrderMapper.xml, src/main/webapp/WEB-INF/views/mypage/myorders2.jsp, src/main/webapp/resources/css/contents.css, src/main/webapp/resources/js/reply.js, src/test/java/com/kosa/mapper/OrderMapperTest.java, src/test/java/com/kosa/service/OrderServiceImplTest.java
- 검색 + 페이징 기능 추가 (상품명, 주문번호 선택 후 키워드 검색)
- DB 중복 데이터 처리되는 것 수정 (OrderMapper.xml 수정)
=> [feat] 검색 + 페이징 기능 추가(#91)

src/main/java/com/kosa/domain/member/MemberVO.java, src/test/java/com/kosa/mapper/MemberMapperTest.java, src/test/java/com/kosa/service/MemberServicelpmlTest.java
- 회원 가입 및 이메일 인증 테스트 진행
- 추가로 MemberVO 객체의 mbrith의 Date에서 LocalDate로 타입 변경
resolved #95
=> [test] member join, duplicate Test (#95)

src/main/java/com/kosa/controller/CartRestController.java, src/main/java/com/kosa/controller/ProductController.java, src/main/webapp/WEB-INF/views/product/productdetailTest.jsp, src/main/webapp/resources/js/handsome/addToCart.js
=> [feat] 물품상세페이지에서 cart 추가하기 (#85)

src/main/webapp/WEB-INF/spring/security-context.xml, src/main/webapp/WEB-INF/views/member/joininfoform.jsp, src/main/webapp/WEB-INF/views/member/joinprovision.jsp
- security-context.xml에 csrf 토큰 활성화
- form태그 전송 방식과 ajax 전송 방식에 각각 csrf 토큰 추가
resolved #99
=> [feat] SpringSecurity csrfToken 추가(#99)

src/main/webapp/WEB-INF/views/checkout/ordersheet.jsp
=> [fix] ordersheet cartdata 넘기기

src/main/java/com/kosa/controller/EventController.java, src/main/java/com/kosa/controller/MypageController2.java, src/main/java/com/kosa/mapper/EventMapper.java, src/main/java/com/kosa/service/EventService.java, src/main/java/com/kosa/service/EventServiceImpl.java, src/main/resources/com/kosa/mapper/EventMapper.xml, src/main/webapp/WEB-INF/views/mypage/mycouponExpiry.jsp, src/main/webapp/WEB-INF/views/mypage/mycouponUnused.jsp, src/main/webapp/WEB-INF/views/mypage/mycouponUsed.jsp, src/test/java/com/kosa/controller/CouponDetailExpiryControllerTest.java, src/test/java/com/kosa/controller/CouponDetailUnusedControllerTest.java, src/test/java/com/kosa/controller/CouponDetailUsedControllerTest.java, src/test/java/com/kosa/mapper/CouponDetailExpiryTest.java, src/test/java/com/kosa/mapper/CouponDetailUnusedTest.java, src/test/java/com/kosa/mapper/CouponDetailUsedTest.java, src/test/java/com/kosa/service/CouponDetailExpiryServiceTest.java, src/test/java/com/kosa/service/CouponDetailUnusedServiceTest.java, src/test/java/com/kosa/service/CouponDetailUsedServiceTest.java
=> [feat] 마이페이지 쿠폰 구분출력 (#107)

src/main/java/com/kosa/controller/CartRestController.java, src/main/webapp/WEB-INF/views/cart/cart.jsp
=> [test] sec mid 값 확인

src/main/webapp/WEB-INF/views/member/joininfoform.jsp, src/main/webapp/WEB-INF/views/member/joinprovision.jsp, src/main/webapp/WEB-INF/views/member/joinstart.jsp, src/main/webapp/WEB-INF/views/member/login.jsp
- Join 관련 JSP 파일들에 header와 footer include
resolved #101
=> [feat] JoinJspFIles header, footer (#101)

src/main/java/com/kosa/security/CustomAccessDeniedHandler.java, src/main/java/com/kosa/security/CustomLoginSuccessHandler.java, src/main/java/com/kosa/security/CustomUserDetailsService.java, src/main/webapp/WEB-INF/spring/security-context.xml
- com.kosa.security의 클래스들 수정
- ROLE_MEMBER 권한 인증 안되던 오류 수정
resolved #118
=> [feat] security authorize bug fix (#118)

src/main/java/com/kosa/controller/MemberController.java, src/main/webapp/WEB-INF/views/member/accessError.jsp, src/main/webapp/WEB-INF/views/member/admin.jsp
- 권한 없는 사용자 접근시 보여줄 에러 page의 url 생성
- AccessDeniedHandler 수정
resolved #120
=> [feat] member authorize error (#120)

src/main/java/com/kosa/controller/MypageController.java, src/main/webapp/WEB-INF/views/mypage/member.jsp, src/main/webapp/WEB-INF/views/mypage/pwCheck.jsp, src/test/java/com/kosa/controller/MypageControllerTest.java
- pwCheck Page 생성
- 참고 사항 : JSP와 Controller가 연결되지 않아 추후 수정 예정
resolved #122
=> [feat] mypage Pwcheck(#122)

src/main/java/com/kosa/controller/CartRestController.java, src/main/java/com/kosa/controller/ProductController.java, src/main/webapp/WEB-INF/spring/security-context.xml, src/main/webapp/WEB-INF/views/common/header.jsp, src/main/webapp/WEB-INF/views/product/productdetail.jsp
=> [fix] productdetail에서 cart로 값 넘길때 sessionmid 값(#113)

src/main/java/com/kosa/controller/EventController.java, src/main/java/com/kosa/domain/event/CouponCountVO.java, src/main/java/com/kosa/domain/event/CouponDetailViewVO.java, src/main/java/com/kosa/mapper/EventMapper.java, src/main/java/com/kosa/service/EventService.java, src/main/java/com/kosa/service/EventServiceImpl.java, src/main/resources/com/kosa/mapper/EventMapper.xml, src/main/webapp/WEB-INF/views/common/header.jsp, src/test/java/com/kosa/mapper/GetCouponCountMapperTest.java, src/test/java/com/kosa/mapper/UpdateCouponMapperTest.java, src/test/java/com/kosa/service/GetCouponCountServiceTest.java, src/test/java/com/kosa/service/UpdateCouponServiceTest.java
=> [feat] eventcount/errorpage(주석)연결 (#127)

src/main/webapp/WEB-INF/views/mypage/mywish.jsp, src/main/webapp/WEB-INF/views/product/productlist.jsp
=> [feat] 위시리스트 수정 (#132)

src/main/java/com/kosa/mapper/MemberMapper.java, src/main/java/com/kosa/service/MemberService.java, src/main/java/com/kosa/service/MemberServicelmpl.java, src/main/resources/com/kosa/mapper/MemberMapper.xml, src/test/java/com/kosa/mapper/MemberMapperTest.java, src/test/java/com/kosa/service/MemberServicelpmlTest.java
- Member Infomation Change 기능 추가
- Mapper, Service 생성
resolved #136
=> Feature member/info change(#136)

src/main/java/com/kosa/controller/ProductController.java, src/main/java/com/kosa/domain/paging/Criteria.java, src/main/resources/com/kosa/mapper/ProductMapper.xml, src/main/webapp/WEB-INF/views/common/header.jsp, src/main/webapp/WEB-INF/views/product/productlist.jsp, src/test/java/com/kosa/mapper/ProductMapperTests.java
=> [fix] 헤더 수정 + 페이징 수정 + 필터링 추가

src/main/java/com/kosa/controller/MypageController.java, src/main/java/com/kosa/service/MemberServicelmpl.java, src/main/resources/com/kosa/mapper/MemberMapper.xml, src/main/webapp/WEB-INF/views/member/joininfoform.jsp, src/main/webapp/WEB-INF/views/mypage/memberInfoChange.jsp, src/main/webapp/WEB-INF/views/mypage/pwCheck.jsp
- 회원 정보 수정 Page, Controller 추가
- memberMapper.xml update 쿼리 수정
resolved #144
=> [feat] MemberInfoChange Page (#144)

src/main/java/com/kosa/controller/CartRestController.java, src/main/java/com/kosa/service/CartService.java, src/main/resources/com/kosa/mapper/CartMapper.xml, src/main/webapp/WEB-INF/views/checkout/ordersheet.jsp, src/main/webapp/WEB-INF/views/product/productdetail.jsp, src/main/webapp/resources/js/handsome/addToCart.js, src/main/webapp/resources/js/handsome/cartlist.js, src/main/webapp/resources/js/handsome/checkoutCartView.js
=> Cleanup code cart

src/main/java/com/kosa/controller/MemberController.java, src/main/java/com/kosa/mapper/MemberMapper.java, src/main/java/com/kosa/service/MemberService.java, src/main/java/com/kosa/service/MemberServicelmpl.java, src/main/webapp/WEB-INF/views/member/joininfoform.jsp, src/main/webapp/WEB-INF/views/member/joinstart.jsp, src/main/webapp/WEB-INF/views/mypage/memberInfoChange.jsp, src/main/webapp/WEB-INF/views/mypage/pwCheck.jsp
- member 주석, jsp 정리
resovled #158
=> [feat] member 주석, jsp 정리

src/main/java/com/kosa/service/MemberServicelmpl.java, src/test/java/com/kosa/service/MemberServicelpmlTest.java
=> [feat] memberService 주석
